# قائمة بأشهر أوامر لينكس مع أشهر الأرجومنتات لكل أمر
LINUX_COMMANDS = {
    'ls': ['-a', '-l', '-lh', '--help'],
    'cd': ['..', '/'],
    'cp': ['-r', '-i', '--help'],
    'mv': ['-i', '-u', '--help'],
    'rm': ['-r', '-f', '-rf', '--help'],
    'cat': ['-n', '-b', '--help'],
    'echo': ['-n', '--help'],
    'touch': ['--help'],
    'mkdir': ['-p', '--help'],
    'rmdir': ['--help'],
    'pwd': ['--help'],
    'grep': ['-i', '-r', '-n', '--help'],
    'find': ['-name', '-type', '--help'],
    'history': ['-c', '-d', '--help'],
    'head': ['-n', '--help'],
    'tail': ['-n', '-f', '--help'],
    'chmod': ['+x', '-R', '--help'],
    'chown': ['-R', '--help'],
    'man': ['--help'],
    'whoami': ['--help'],
    'clear': [],
    'df': ['-h', '--help'],
    'du': ['-h', '--help'],
    'ps': ['-aux', '--help'],
    'kill': ['-9', '--help'],
    'top': [],
    'htop': [],
    'uname': ['-a', '--help'],
    'date': ['--help'],
    'wget': ['--help'],
    'curl': ['--help'],
    'ssh': ['-i', '-p', '--help'],
    'scp': ['-r', '-P', '--help'],
    'tar': ['-xvf', '-cvf', '--help'],
    'zip': ['-r', '--help'],
    'unzip': ['--help'],
    'nano': ['--help'],
    'vim': ['--help'],
    'apt': ['update', 'upgrade', 'install', 'remove', '--help'],
    'sudo': [],
    'exit': [],
    'logout': [],
    'reboot': [],
    'shutdown': ['-r', '-h', 'now'],
}

# إضافة معلومات عن الأوامر التي تحتاج ملف أو قيمة
LINUX_COMMANDS_NEED_FILE = {
    'cat': '[FILE]',
    'cp': '[SRC] [DEST]',
    'mv': '[SRC] [DEST]',
    'rm': '[FILE]',
    'head': '[FILE]',
    'tail': '[FILE]',
    'chmod': '[MODE] [FILE]',
    'chown': '[OWNER] [FILE]',
    'grep': '[PATTERN] [FILE]',
    'find': '[PATH]',
    'tar': '[ARCHIVE] [FILES]',
    'scp': '[SRC] [DEST]',
    'nano': '[FILE]',
    'vim': '[FILE]',
    'wget': '[URL]',
    'curl': '[URL]',
    'zip': '[ARCHIVE] [FILES]',
    'unzip': '[ARCHIVE]',
    'ps': '',
    'ls': '',
    # ... أضف المزيد حسب الحاجة ...
}
